import '../css/app.scss';
// import Rx from 'rxjs/Rx';
// window.Rx = Rx;
// import './part1';
import './part2';
// import './part3';
// import './part4';
// import './part5';
// import './part6';
// import './part7';
// import './part8';
// import './part9';
// import './part10';
// import './part11';
// import './part12';
// import './part13';
// import './part14';
import './part15';
